
# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  schedule: [{cron: "0 4 * * *"}]
  push: 
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: RaphaelS1
          token: ${{ secrets.METRICS }}
          isHireable: false
          config_timezone: Europe/London
          config_output: insights
          commits_authoring: raphaelsonabend@gmail.com, raphael.sonabend.15@ucl.ac.uk, r.sonabend@imperial.ac.uk
          plugin_languages: yes
          plugin_languages_ignored: html, css, dockerfile, JavaScript, TypeScript
          plugin_introduction: yes
          plugin_gists: yes
          plugin_followup: yes
          plugin_lines:  yes
          plugin_achievements: yes
          plugin_notable: yes
          plugin_repositories: yes
          plugin_repositories_featured: distr6, set6, mlr3proba, mlr-org/mlr3extralearners
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 11815170
          
