
# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  schedule: [{cron: "0 0 * * 0"}]
  push: 
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: RaphaelS1
          token: ${{ secrets.METRICS }}
          isHireable: false
          config_timezone: Europe/London
          commits_authoring: raphaelsonabend@gmail.com, raphael.sonabend.15@ucl.ac.uk, r.sonabend@imperial.ac.uk
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_ignored: html, css, dockerfile, JavaScript, TypeScript
          plugin_introduction: yes
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_gists: yes
          plugin_followup: yes
          plugin_lines:  yes
          plugin_achievements: yes
          plugin_notable: yes
          plugin_repositories: yes
          plugin_repositories_featured: xoopR/distr6, mlr-org/mlr3proba, survivalmodels, mlr-org/mlr3book, SurvivalAnalysis.jl
