
# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Simple Metrics
on:
  schedule: [{cron: "0 4 1 * *"}]
  push: 
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: RaphaelS1
          token: ${{ secrets.METRICS }}
          isHireable: false
          filename: web-metrics.svg
          config_timezone: Europe/London
          commits_authoring: raphaelsonabend@gmail.com, raphael.sonabend.15@ucl.ac.uk, r.sonabend@imperial.ac.uk
          plugin_achievements: yes
          plugin_notable: yes

          
